# Generated by Django 4.2 on 2023-04-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='environment',
            field=models.CharField(blank=True, choices=[('A', 'Anywhere'), ('I', 'Inside'), ('O', 'Outside')], default='A', max_length=1),
        ),
    ]
